apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-episode-03
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-episode-03
  template:
    metadata:
      labels:
        app: frontend-episode-03
    spec:
      containers:
      - name: frontend
        image: rubabzahra/frontend-episode-03:latest
        ports:
        - containerPort: 80
